# Generated by Django 4.2.6 on 2023-10-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('subject', models.TextField()),
                ('inputcity', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=80)),
            ],
        ),
    ]
