# Generated by Django 4.2.6 on 2023-10-28 19:42

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ngo_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('textarea', models.TextField(max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.filepath)),
            ],
        ),
    ]
